window.extraGrammarSections = [
    {
        id: "konjunktiv",
        title: "Konjunktiv II",
        shortTitle: "Konjunktiv II",
        theory: {
            intro: "The German Konjunktiv II is used constantly in everyday German for polite requests, wishes, and hypothetical \"what if\" scenarios.",
            rules: [
                ["1. The Helper Construction", "Most verbs form Konjunktiv II by using würde (would) + the infinitive verb at the very end of the sentence.", "Example: Ich würde ein Auto kaufen. (I would buy a car.)"],
                ["2. The Core Irregulars", "The most important verbs don't use würde. They change their own form, usually adding an Umlaut. You must memorize these: haben -> hätte, sein -> wäre, können -> könnte, müssen -> müsste, dürfen -> dürfte, wissen -> wüsste, wollen -> wollte (no umlaut), sollen -> sollte (no umlaut).", ""],
                ["3. Konjunktiv II in the Past", "To express regrets or unreal past events (\"If I had gone...\"), use the helper wäre or hätte + the Past Participle at the end.", "Example: Ich wäre nach Berlin gefahren. (I would have driven to Berlin.) / Ich hätte das Haus gekauft."],
                ["4. The \"Wenn\" Drop (Inversion)", "To sound more fluent and elegant (B2 level), you can drop the word wenn (if). When you do this, the sentence must start immediately with the conjugated verb.", "Standard: Wenn ich Zeit hätte, würde ich kommen. / Advanced: Hätte ich Zeit, würde ich kommen. / Wäre ich reich, würde ich ein Boot kaufen."],
                ["5. Passive Konjunktiv II", "To express that something should or would be done to an object (Passive + Hypothetical), use würde/müsste/könnte + Past Participle + werden.", "Example: Das Auto müsste repariert werden. (The car would have to be repaired.)"]
            ],
            triggers: []
        },
        sentences: [
            ["I would like to have a coffee, please.", "Ich hätte gern einen Kaffee, bitte."],
            ["Could you help me?", "Könntest du mir helfen?"],
            ["I would buy the house if I had money.", "Ich würde das Haus kaufen, wenn ich Geld hätte."],
            ["If I were you, I wouldn't do that.", "Wenn ich du wäre, würde ich das nicht tun."],
            ["We should leave now.", "Wir sollten jetzt gehen."],
            ["That might be true.", "Das dürfte wahr sein."],
            ["I wish I had more time.", "Ich wünschte, ich hätte mehr Zeit."],
            ["He acts as if he were the boss.", "Er tut so, als ob er der Chef wäre."],
            ["Would you open the window?", "Würdest du das Fenster öffnen?"],
            ["I could do that for you.", "Ich könnte das für dich tun."],
            ["We would gladly come to your party.", "Wir würden gerne zu deiner Party kommen."],
            ["You would have to ask the teacher.", "Du müsstest den Lehrer fragen."],
            ["I would travel to Japan if I had time.", "Ich würde nach Japan reisen, wenn ich Zeit hätte."],
            ["If it rained, we would stay at home.", "Wenn es regnen würde, würden wir zu Hause bleiben."],
            ["I would have bought it. (Past)", "Ich hätte es gekauft."],
            ["We would have come, but we were sick. (Past)", "Wir wären gekommen, aber wir waren krank."],
            ["If I had known that, I would have helped you. (Past)", "Wenn ich das gewusst hätte, hätte ich dir geholfen."],
            ["You should have seen that! (Past)", "Das hättest du sehen sollen!"],
            ["I would have liked to stay longer. (Past)", "Ich wäre gerne länger geblieben."],
            ["If she had hurried, she would have caught the train. (Past)", "Wenn sie sich beeilt hätte, hätte sie den Zug erwischt."],
            ["I would eat a pizza right now.", "Ich würde jetzt eine Pizza essen."],
            ["Could I borrow your pen?", "Könnte ich deinen Stift ausleihen?"],
            ["He would gladly work less.", "Er würde gerne weniger arbeiten."],
            ["That would be wonderful!", "Das wäre wunderbar!"],
            ["I would never say that.", "Das würde ich nie sagen."],
            ["Should I close the door?", "Sollte ich die Tür zumachen?"],
            ["If I won the lottery, I would buy a boat.", "Wenn ich im Lotto gewinnen würde, würde ich ein Boot kaufen."],
            ["I would help you if I could.", "Ich würde dir helfen, wenn ich könnte."],
            ["That would be too good to be true.", "Das wäre zu schön, um wahr zu sein."],
            ["We would have to hurry.", "Wir müssten uns beeilen."],
            ["If he were here, he would know the answer.", "Wenn er hier wäre, wüsste er die Antwort."],
            ["I would rather stay at home.", "Ich würde lieber zu Hause bleiben."],
            ["Without you, I would be lost.", "Ohne dich wäre ich verloren."],
            ["What would you do in my place?", "Was würdest du an meiner Stelle tun?"],
            ["We would have had to work faster. (Past)", "Wir hätten schneller arbeiten müssen."],
            ["It would have been better if you had called. (Past)", "Es wäre besser gewesen, wenn du angerufen hättest."],
            ["I would have flown to Spain. (Past)", "Ich wäre nach Spanien geflogen."],
            ["She wouldn't have done that. (Past)", "Sie hätte das nicht getan."],
            ["I would be happy if you visited me.", "Ich würde mich freuen, wenn du mich besuchst."],
            ["He could at least call!", "Er könnte wenigstens anrufen!"],
            ["We would have enough space in the car.", "Wir hätten genug Platz im Auto."],
            ["That would make no sense.", "Das würde keinen Sinn machen."],
            ["I would have expected that from him. (Past)", "Das hätte ich von ihm erwartet."],
            ["If I only had more money!", "Wenn ich nur mehr Geld hätte!"],
            ["Could you please repeat that?", "Könnten Sie das bitte wiederholen?"],
            ["I would love to go to the beach.", "Ich würde sehr gerne an den Strand gehen."],
            ["You shouldn't smoke so much.", "Du solltest nicht so viel rauchen."],
            ["We would have ordered pizza, if it weren't so late. (Past/Present mix)", "Wir hätten Pizza bestellt, wenn es nicht so spät wäre."],
            ["I would have forgotten it. (Past)", "Ich hätte es vergessen."],
            ["That would be all, thank you.", "Das wäre alles, danke."],
            ["Had I time, I would come. (Inversion)", "Hätte ich Zeit, würde ich kommen."],
            ["Were I rich, I would buy a house. (Inversion)", "Wäre ich reich, würde ich ein Haus kaufen."],
            ["Had I known that, I wouldn't have done it. (Inversion Past)", "Hätte ich das gewusst, hätte ich es nicht getan."],
            ["The problem would have to be solved immediately. (Passive)", "Das Problem müsste sofort gelöst werden."],
            ["The house could be renovated. (Passive)", "Das Haus könnte renoviert werden."],
            ["The car would be repaired. (Passive)", "Das Auto würde repariert werden."],
            ["The bill should be paid. (Passive)", "Die Rechnung sollte bezahlt werden."],
            ["Had we hurried, we would have caught the bus. (Inversion Past)", "Hätten wir uns beeilt, hätten wir den Bus erwischt."],
            ["Were he my friend, he would help me. (Inversion)", "Wäre er mein Freund, würde er mir helfen."],
            ["The email would have to be written today. (Passive)", "Die E-Mail müsste heute geschrieben werden."]
        ]
    },
    {
        id: "future",
        title: "Future Tense (Futur I & II)",
        shortTitle: "Future Tenses",
        theory: {
            intro: "German is famously relaxed about the future. For most planned events, Germans just use the present tense + a time word (e.g., Ich komme morgen). However, the explicit future tenses are vital for promises, predictions, and assumptions.",
            rules: [
                ["1. Futur I (Promises and Predictions)", "Formed with the conjugated helper verb werden + the infinitive at the end of the sentence.", "The Future: Es wird morgen regnen. / The Promise: Ich werde dich immer lieben."],
                ["2. Futur I (Present Assumptions)", "If you guess what someone is doing right now, you use Futur I + words like wohl or schon.", "Er wird wohl zu Hause sein. (He is probably at home)"],
                ["3. Futur II (Completed Future)", "Formed with werden + Past Participle + haben/sein at the end. It expresses an action that will be finished by a certain point in the future.", "Bis morgen werde ich das Buch gelesen haben. (By tomorrow, I will have read the book.)"],
                ["4. Futur II (Past Assumptions)", "Use Futur II to express an assumption about something that happened in the past.", "Sie wird den Zug verpasst haben. (She probably missed the train)"],
                ["5. The Double Infinitive (Modal Traps)", "If you want to use a modal verb (must, can, should) in the future tense, you cannot use a past participle. You must push BOTH infinitives to the absolute end of the sentence. The modal verb always comes last.", "Ich werde morgen arbeiten müssen. / Wir werden das Auto reparieren können."]
            ],
            triggers: []
        },
        sentences: [
            ["I will call you tomorrow.", "Ich werde dich morgen anrufen."],
            ["It will rain tomorrow.", "Es wird morgen regnen."],
            ["We will see.", "Wir werden sehen."],
            ["I will never forget that.", "Ich werde das nie vergessen."],
            ["You will find a good job.", "Du wirst einen guten Job finden."],
            ["Will you come to the party?", "Wirst du zur Party kommen?"],
            ["He will probably be at work now. (Assumption)", "Er wird jetzt wohl auf der Arbeit sein."],
            ["She is probably sleeping right now. (Assumption)", "Sie wird jetzt wohl schlafen."],
            ["They will certainly win the game.", "Sie werden das Spiel sicher gewinnen."],
            ["Everything will be fine.", "Alles wird gut werden."],
            ["I will not do that.", "Ich werde das nicht tun."],
            ["We will travel to Italy next year.", "Wir werden nächstes Jahr nach Italien reisen."],
            ["Will he help us?", "Wird er uns helfen?"],
            ["I will learn German every day.", "Ich werde jeden Tag Deutsch lernen."],
            ["She will probably know the answer. (Assumption)", "Sie wird die Antwort wohl wissen."],
            ["By tomorrow, I will have finished the work. (Futur II)", "Bis morgen werde ich die Arbeit beendet haben."],
            ["He will have forgotten it by then. (Futur II)", "Er wird es bis dahin vergessen haben."],
            ["In a year, we will have bought a house. (Futur II)", "In einem Jahr werden wir ein Haus gekauft haben."],
            ["She probably missed the train. (Past Assumption / Futur II)", "Sie wird den Zug verpasst haben."],
            ["He probably didn't hear you. (Past Assumption / Futur II)", "Er wird dich nicht gehört haben."],
            ["They probably went home. (Past Assumption / Futur II)", "Sie werden nach Hause gegangen sein."],
            ["By 8 o'clock, the guests will have arrived. (Futur II)", "Bis 8 Uhr werden die Gäste angekommen sein."],
            ["You will have learned a lot by the end of the year. (Futur II)", "Am Ende des Jahres wirst du viel gelernt haben."],
            ["The mechanic will have repaired the car by Friday. (Futur II)", "Der Mechaniker wird das Auto bis Freitag repariert haben."],
            ["I will have written the email by this evening. (Futur II)", "Ich werde die E-Mail bis heute Abend geschrieben haben."],
            ["I will wait for you.", "Ich werde auf dich warten."],
            ["It will cost a lot of money.", "Es wird viel Geld kosten."],
            ["Will you marry me?", "Wirst du mich heiraten?"],
            ["We will not give up.", "Wir werden nicht aufgeben."],
            ["You will regret this!", "Du wirst das bereuen!"],
            ["They will probably be stuck in traffic. (Assumption)", "Sie werden wohl im Stau stehen."],
            ["My parents will be proud of me.", "Meine Eltern werden stolz auf mich sein."],
            ["The sun will shine tomorrow.", "Morgen wird die Sonne scheinen."],
            ["I will ask the teacher.", "Ich werde den Lehrer fragen."],
            ["Will you bring the drinks?", "Wirst du die Getränke mitbringen?"],
            ["She probably didn't see the sign. (Past Assumption / Futur II)", "Sie wird das Schild nicht gesehen haben."],
            ["He probably already ate. (Past Assumption / Futur II)", "Er wird schon gegessen haben."],
            ["The thief probably escaped through the window. (Past Assumption / Futur II)", "Der Dieb wird durch das Fenster entkommen sein."],
            ["By the time you arrive, I will have cooked dinner. (Futur II)", "Wenn du ankommst, werde ich das Abendessen gekocht haben."],
            ["We will probably never know.", "Wir werden es wohl nie wissen."],
            ["I will be there at 5 o'clock.", "Ich werde um 5 Uhr da sein."],
            ["Will you understand that one day?", "Wirst du das eines Tages verstehen?"],
            ["The dog will probably be hungry. (Assumption)", "Der Hund wird wohl hungrig sein."],
            ["I will improve my German.", "Ich werde mein Deutsch verbessern."],
            ["He will probably have lost his keys. (Past Assumption / Futur II)", "Er wird seinen Schlüssel verloren haben."],
            ["The package will probably have arrived yesterday. (Past Assumption / Futur II)", "Das Paket wird gestern angekommen sein."],
            ["We will have reached our goal. (Futur II)", "Wir werden unser Ziel erreicht haben."],
            ["I will have to work tomorrow. (Double Infinitive)", "Ich werde morgen arbeiten müssen."],
            ["We will be able to help you. (Double Infinitive)", "Wir werden dir helfen können."],
            ["She will have to learn a lot. (Double Infinitive)", "Sie wird viel lernen müssen."],
            ["Will you be able to come? (Double Infinitive)", "Wirst du kommen können?"],
            ["They will have to wait. (Double Infinitive)", "Sie werden warten müssen."],
            ["I will want to see that. (Double Infinitive)", "Ich werde das sehen wollen."],
            ["He will not be allowed to do that. (Double Infinitive)", "Er wird das nicht tun dürfen."],
            ["We will be able to repair the car. (Double Infinitive)", "Wir werden das Auto reparieren können."]
        ]
    },
    {
        id: "comparison",
        title: "Degrees of Comparison",
        shortTitle: "Comparisons",
        theory: {
            intro: "When comparing things in German, adjectives undergo changes in three stages: the Positive (equal), the Comparative (more/less), and the Superlative (most).",
            rules: [
                ["1. Positiv (Equal)", "Use so [adjective] wie (as [adjective] as).", "Er ist so groß wie ich. (He is as tall as me.)"],
                ["2. Komparativ (Unequal)", "Add -er to the adjective and use als (than).", "Er ist schneller als ich. (He is faster than me.)"],
                ["3. Superlativ (The Most)", "Use am + adjective + -sten (when at the end of a sentence).", "Er ist am schnellsten. (He is the fastest.)"],
                ["4. The Umlaut Shift", "Many short, one-syllable adjectives with a, o, or u get an Umlaut in the comparative and superlative forms.", "alt -> älter -> am ältesten / groß -> größer -> am größten / kalt -> kälter -> am kältesten / jung -> jünger -> am jüngsten"],
                ["5. The \"-el\" and \"-er\" Drop", "Adjectives ending in -el or -er drop their 'e' in the comparative form to make pronunciation easier.", "teuer -> teurer (not teuerer) / dunkel -> dunkler (not dunkeler)"],
                ["6. The \"-e-\" Insertion", "Adjectives ending in -d, -t, -s, -z, or -sch need an extra 'e' in the superlative so they can actually be pronounced.", "heiß -> am heißesten (not am heißsten) / kalt -> am kältesten"],
                ["7. The Crucial Irregulars", "You must memorize these exceptions perfectly: gut -> besser -> am besten; viel -> mehr -> am meisten; gern -> lieber -> am liebsten; hoch -> höher -> am höchsten; nah -> näher -> am nächsten.", ""],
                ["8. Attributive Adjectives (Before a Noun)", "If the comparison happens directly before a noun, it must take standard adjective endings on top of the comparative marker.", "Ein schnelleres Auto. (A faster car.) / Das beste Buch. (The best book.)"]
            ],
            triggers: []
        },
        sentences: [
            ["He is exactly as tall as his brother.", "Er ist genau so groß wie sein Bruder."],
            ["My car is faster than your car.", "Mein Auto ist schneller als dein Auto."],
            ["Today is the coldest day of the year.", "Heute ist der kälteste Tag des Jahres."],
            ["I speak better German now.", "Ich spreche jetzt besser Deutsch."],
            ["She is older than me.", "Sie ist älter als ich."],
            ["This book is more interesting than that one.", "Dieses Buch ist interessanter als das da."],
            ["We need more time.", "Wir brauchen mehr Zeit."],
            ["I like drinking coffee, but I prefer drinking tea.", "Ich trinke gern Kaffee, aber ich trinke lieber Tee."],
            ["He eats pizza most of all. (He likes eating pizza best.)", "Er isst am liebsten Pizza."],
            ["That is the highest building in the city.", "Das ist das höchste Gebäude der Stadt."],
            ["The supermarket is near, but the bakery is nearer.", "Der Supermarkt ist nah, aber die Bäckerei ist näher."],
            ["Where is the nearest train station?", "Wo ist der nächste Bahnhof?"],
            ["This is the best restaurant in town.", "Das ist das beste Restaurant der Stadt."],
            ["The test was harder than I thought.", "Der Test war schwerer als ich dachte."],
            ["My dog is smaller than a cat.", "Mein Hund ist kleiner als eine Katze."],
            ["She works as hard as her colleague.", "Sie arbeitet so hart wie ihr Kollege."],
            ["The new computer is much more expensive.", "Der neue Computer ist viel teurer."],
            ["Who is the youngest person here?", "Wer ist die jüngste Person hier?"],
            ["He has less money than before.", "Er hat weniger Geld als früher."],
            ["It is getting warmer.", "Es wird wärmer."],
            ["The red dress is prettier than the blue one.", "Das rote Kleid ist schöner als das blaue."],
            ["That is the longest river in Germany.", "Das ist der längste Fluss in Deutschland."],
            ["I need a larger apartment.", "Ich brauche eine größere Wohnung."],
            ["We want to buy a cheaper car.", "Wir wollen ein billigeres Auto kaufen."],
            ["She gave me the best advice.", "Sie hat mir den besten Rat gegeben."],
            ["Today I feel worse than yesterday.", "Heute fühle ich mich schlechter als gestern."],
            ["Which language is the easiest?", "Welche Sprache ist am einfachsten?"],
            ["The movie is not as good as the book.", "Der Film ist nicht so gut wie das Buch."],
            ["He runs the fastest.", "Er läuft am schnellsten."],
            ["The nights are getting longer.", "Die Nächte werden länger."],
            ["I have most of the work finished.", "Ich habe die meiste Arbeit fertig."],
            ["Most people think that is wrong.", "Die meisten Leute denken, dass das falsch ist."],
            ["That is the shortest way to the beach.", "Das ist der kürzeste Weg zum Strand."],
            ["My tea is hotter than your coffee.", "Mein Tee ist heißer als dein Kaffee."],
            ["She is the smartest student in the class.", "Sie ist die klügste Schülerin in der Klasse."],
            ["We live in a quieter street now.", "Wir wohnen jetzt in einer ruhigeren Straße."],
            ["This problem is more complicated.", "Dieses Problem ist komplizierter."],
            ["I earn less than my boss.", "Ich verdiene weniger als mein Chef."],
            ["The weather is better today than yesterday.", "Das Wetter ist heute besser als gestern."],
            ["We walked further than planned.", "Wir sind weiter gelaufen als geplant."],
            ["He is my best friend.", "Er ist mein bester Freund."],
            ["That is the most important thing.", "Das ist die wichtigste Sache. / Das ist das Wichtigste."],
            ["You must speak louder.", "Du musst lauter sprechen."],
            ["I would rather go to the cinema.", "Ich gehe lieber ins Kino."],
            ["The first book was thicker.", "Das erste Buch war dicker."],
            ["This chair is more comfortable.", "Dieser Stuhl ist bequemer."],
            ["It is exactly as expensive as I thought.", "Es ist genau so teuer wie ich dachte."],
            ["That is the saddest movie I know.", "Das ist der traurigste Film, den ich kenne."],
            ["We have to find a better solution.", "Wir müssen eine bessere Lösung finden."],
            ["The new car is more expensive. (-er drop)", "Das neue Auto ist teurer."],
            ["It is getting darker outside. (-el drop)", "Es wird draußen dunkler."],
            ["August is the hottest month. (-e- insertion)", "Der August ist der heißeste Monat."],
            ["This route is the shortest. (-e- insertion)", "Dieser Weg ist am kürzesten."],
            ["She bought the most expensive bag.", "Sie hat die teuerste Tasche gekauft."],
            ["The room is darker than before. (-el drop)", "Das Zimmer ist dunkler als zuvor."]
        ]
    },
    {
        id: "passive",
        title: "The Passive Voice",
        shortTitle: "Passive Voice",
        theory: {
            intro: "The passive voice is used when the action is more important than who is doing it. In English, we say 'The car is being repaired' (we don't care who the mechanic is).",
            rules: [
                ["1. The Process Passive (Vorgangspassiv)", "This focuses on the action taking place. It is always formed using the helper verb werden + the Past Participle at the absolute end of the sentence.", "Präsens: Das Auto wird repariert. / Präteritum: Das Auto wurde repariert."],
                ["2. Process Passive in Perfekt & Futur I", "In Perfekt, 'geworden' loses its 'ge-'. Futur I uses werden + participle + werden.", "Perfekt: Das Auto ist repariert worden. / Futur I: Das Auto wird repariert werden."],
                ["3. Passive with Modal Verbs", "When you add a modal verb (must, can, should), the modal takes the conjugated position, the past participle goes to the end, and the infinitive werden anchors the very end.", "Präsens: Das Problem muss gelöst werden. / Präteritum: Das Problem musste gelöst werden."],
                ["4. State Passive (Zustandspassiv)", "If the action is completely finished and you are describing the resulting state, you swap 'werden' for 'sein'.", "Das Fenster ist geschlossen. (The window is closed - the act of closing is over)."],
                ["5. The Dative Trap (B2 Crucial)", "If a verb normally requires a Dative object (like helfen or danken), that object REMAINS Dative in the passive voice. It does not become the subject.", "Wrong: Ich werde geholfen. / Correct: Mir wird geholfen. (I am being helped.) / Ihm wurde gedankt."],
                ["6. The Impersonal Passive (Subjectless)", "Germans frequently use the passive voice without any subject at all to describe a general activity, often starting the sentence with Es.", "Es wird hier viel getanzt. (There is a lot of dancing here.) / Hier wird nicht geraucht. (No smoking here.)"]
            ],
            triggers: []
        },
        sentences: [
            ["The car is being repaired.", "Das Auto wird repariert."],
            ["The letter is being written.", "Der Brief wird geschrieben."],
            ["The house was built in 1990. (Präteritum)", "Das Haus wurde 1990 gebaut."],
            ["The door was opened by the wind. (Präteritum)", "Die Tür wurde durch den Wind geöffnet."],
            ["The bill has already been paid. (Perfekt)", "Die Rechnung ist schon bezahlt worden."],
            ["The package has been delivered. (Perfekt)", "Das Paket ist geliefert worden."],
            ["The problem must be solved immediately.", "Das Problem muss sofort gelöst werden."],
            ["The rules must be followed.", "Die Regeln müssen befolgt werden."],
            ["The computer can be repaired.", "Der Computer kann repariert werden."],
            ["That cannot be changed.", "Das kann nicht geändert werden."],
            ["The window is closed. (State Passive)", "Das Fenster ist geschlossen."],
            ["The book was written by Goethe. (Präteritum)", "Das Buch wurde von Goethe geschrieben."],
            ["The potatoes are being cooked.", "Die Kartoffeln werden gekocht."],
            ["The patient is being examined by the doctor.", "Der Patient wird von der Ärztin untersucht."],
            ["The email has not been read yet. (Perfekt)", "Die E-Mail ist noch nicht gelesen worden."],
            ["Everything is being prepared for the party.", "Alles wird für die Party vorbereitet."],
            ["The building had to be evacuated. (Modal Präteritum)", "Das Gebäude musste evakuiert werden."],
            ["The truth must be told.", "Die Wahrheit muss gesagt werden."],
            ["The bicycle was stolen yesterday. (Präteritum)", "Das Fahrrad wurde gestern gestohlen."],
            ["The museum is opened at 9 o'clock.", "Das Museum wird um 9 Uhr geöffnet."],
            ["The shop is closed. (State Passive)", "Das Geschäft ist geschlossen."],
            ["The dishes have already been washed. (Perfekt)", "Das Geschirr ist schon abgewaschen worden."],
            ["A new hospital is being built here.", "Hier wird ein neues Krankenhaus gebaut."],
            ["Smoking is not allowed here.", "Hier darf nicht geraucht werden."],
            ["The homework should be done.", "Die Hausaufgaben sollten gemacht werden."],
            ["The contract was signed by both parties. (Präteritum)", "Der Vertrag wurde von beiden Parteien unterschrieben."],
            ["The mistake was made by me. (Präteritum)", "Der Fehler wurde von mir gemacht."],
            ["Money was donated for the project. (Präteritum)", "Für das Projekt wurde Geld gespendet."],
            ["The rooms are cleaned every day.", "Die Zimmer werden jeden Tag geputzt."],
            ["Tickets can be bought online.", "Tickets können online gekauft werden."],
            ["The cake has been eaten. (Perfekt)", "Der Kuchen ist gegessen worden."],
            ["This word is rarely used.", "Dieses Wort wird selten benutzt."],
            ["The match was interrupted by the rain. (Präteritum)", "Das Spiel wurde durch den Regen unterbrochen."],
            ["The guests are welcomed.", "Die Gäste werden begrüßt."],
            ["A doctor must be called!", "Ein Arzt muss gerufen werden!"],
            ["The meeting was canceled. (Präteritum)", "Das Meeting wurde abgesagt."],
            ["The reservation has been confirmed. (Perfekt)", "Die Reservierung ist bestätigt worden."],
            ["No photos may be taken in the museum.", "Im Museum dürfen keine Fotos gemacht werden."],
            ["The city was completely destroyed. (Präteritum)", "Die Stadt wurde komplett zerstört."],
            ["The walls were painted white. (Präteritum)", "Die Wände wurden weiß gestrichen."],
            ["Dinner is served at 7.", "Das Abendessen wird um 7 Uhr serviert."],
            ["His life was saved. (Präteritum)", "Sein Leben wurde gerettet."],
            ["The data will be deleted tomorrow. (Futur I Passive)", "Die Daten werden morgen gelöscht werden."],
            ["Has the mail been delivered today? (Perfekt)", "Ist die Post heute geliefert worden?"],
            ["Children must be protected.", "Kinder müssen geschützt werden."],
            ["The flight has been delayed. (Perfekt)", "Der Flug ist verspätet worden."],
            ["The questions will be answered later. (Futur I Passive)", "Die Fragen werden später beantwortet werden."],
            ["My phone was stolen. (Präteritum)", "Mein Handy wurde gestohlen."],
            ["Coffee is drunk all over the world.", "Kaffee wird auf der ganzen Welt getrunken."],
            ["The bed is already made. (State Passive)", "Das Bett ist schon gemacht."],
            ["I am being helped. (Dative Trap)", "Mir wird geholfen."],
            ["We were helped. (Dative Trap Präteritum)", "Uns wurde geholfen."],
            ["He was thanked. (Dative Trap Präteritum)", "Ihm wurde gedankt."],
            ["The manager is being answered. (Dative Trap)", "Dem Chef wird geantwortet."],
            ["There is a lot of dancing here. (Impersonal)", "Es wird hier viel getanzt."],
            ["There was laughing. (Impersonal Präteritum)", "Es wurde gelacht."],
            ["Work is being done here. (Impersonal)", "Hier wird gearbeitet."],
            ["The house will be built next year. (Futur I Passive)", "Das Haus wird nächstes Jahr gebaut werden."],
            ["The car will be repaired tomorrow. (Futur I Passive)", "Das Auto wird morgen repariert werden."],
            ["The email will be sent later. (Futur I Passive)", "Die E-Mail wird später gesendet werden."]
        ]
    }
];